name: unite-analysis-pcam
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base
  - r-essentials
  - bioconductor-minfi
  - bioconductor-limma
  - bioconductor-illuminahumanmethylation450kmanifest
  - bioconductor-illuminahumanmethylationepicmanifest
  - r-jsonlite